language: go
sudo: false

go:
    - 1.6
    - 1.7
    - 1.8
    - 1.9
    - master

matrix:
    allow_failures:
        - go: master
    fast_finish: true

before_install:
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
    - go get honnef.co/go/tools/cmd/megacheck
    - go get github.com/fzipp/gocyclo
    - go get github.com/TyphoonMC/go.uuid

script:
    - test -z $(gofmt -s -l $GO_FILES)
    - go test -v -race ./...
    - go vet ./...
    - megacheck -unused.consts=false ./...
    - gocyclo -over 20 $GO_FILES
    - go build

notifications:
    email: false
